"""Provider-routed MCP image generation tool.

``generate_image`` accepts a stable provider ID and uses the same generation
service as the Studio HTTP route. Generated bytes are stored once and returned
inline so the calling agent can inspect and refine them.

Design (see TASK-599)
---------------------

This mirrors the Playwright-screenshot path, NOT the Studio
``/v1/media/generations`` route:

- The tool returns a FastMCP ``Image`` content block. That block is what the
  model actually *sees* — enabling "make it warmer"-style iteration — and is
  also what the claude-code bridge persists to the media store + stamps on the
  ``TOOL_END`` event so the chat shows a clickable thumbnail (TASK-483).
- The tool ALSO stores the *identical* raw bytes via :func:`get_media_store`.
  Because :class:`MediaStore` dedups on the post-normalization sha256, the
  bridge's re-upload of the same bytes resolves to the SAME asset — one asset,
  no duplication — while giving the agent a stable ``asset_id`` to reference.
- Iteration: pass ``reference_asset_id`` (an ``asset_id`` from a previous
  ``generate_image`` result). The tool loads that asset as provider image input
  so the selected provider refines it instead of starting from scratch.

Imported by ``server.py`` so registration happens on startup.
"""

from __future__ import annotations

import logging

from mcp.server.fastmcp import Image

from llm_bawt.media import get_media_store
from llm_bawt.media.generation_service import MediaGenerationService

from .server import mcp

logger = logging.getLogger(__name__)

_generation_service = MediaGenerationService()

# Source tag recorded on the stored asset (one of media.store.ALLOWED_SOURCES).
_SOURCE = "tool_generated"


def _sniff_image_format(raw: bytes) -> str:
    """Best-effort image subtype from magic bytes ('png' | 'jpeg' | 'webp' | 'gif').

    Only used for the declared MIME hint and the FastMCP ``Image`` format; the
    media store re-derives the real format from the bytes via Pillow regardless,
    so a wrong guess is cosmetic, never corrupting.
    """
    if raw[:8].startswith(b"\x89PNG\r\n\x1a\n"):
        return "png"
    if raw[:3] == b"\xff\xd8\xff":
        return "jpeg"
    if raw[:4] == b"RIFF" and raw[8:12] == b"WEBP":
        return "webp"
    if raw[:6] in (b"GIF87a", b"GIF89a"):
        return "gif"
    return "png"


@mcp.tool(name="generate_image", structured_output=False)
async def generate_image(
    prompt: str,
    provider: str = "grok",
    model: str | None = None,
    reference_asset_id: str | None = None,
    aspect_ratio: str | None = None,
    resolution: str | None = None,
    user_id: str = "nick",
) -> list:
    """Generate an image with the requested provider (``grok`` or ``openai``).

    The generated image is returned inline so you SEE it in this turn — read it,
    critique it, and iterate. It also appears as a clickable thumbnail in the
    chat automatically.

    To refine a previous image, pass its ``reference_asset_id`` and a prompt
    describing the change. Omit ``provider`` to preserve the historical Grok
    default, or set it explicitly to compare providers.

    Args:
        prompt: What to draw, or how to change the referenced image.
        provider: Stable provider ID: ``grok`` (default) or ``openai``.
        model: Optional provider model; provider default is used when omitted.
        reference_asset_id: Optional prior generated asset used as image input.
        aspect_ratio: Provider-supported aspect ratio; provider default if omitted.
        resolution: Provider-supported resolution; provider default if omitted.
        user_id: Owner scope for the stored asset.

    Returns:
        A list of ``[<image>, <info>]`` where ``<info>`` is a dict containing
        ``asset_id`` (pass it back as ``reference_asset_id`` to iterate),
        ``revised_prompt`` (if xAI rewrote the prompt), and the image ``urls``.
        On failure, returns ``[{"error": "..."}]``.
    """
    logger.info(
        "MCP generate_image provider=%s model=%s prompt=%r reference=%s ar=%s res=%s",
        provider, model, prompt[:120], reference_asset_id, aspect_ratio, resolution,
    )

    store = get_media_store()

    # 1) Resolve the reference image (iteration) into a data URL, if asked.
    source_image: str | None = None
    if reference_asset_id:
        try:
            source_image = store.read_preview_as_data_url(reference_asset_id)
        except Exception as e:  # unknown id, missing blob, backend down
            logger.warning(
                "generate_image: reference_asset_id=%s unreadable: %s",
                reference_asset_id, e,
            )
            return [{
                "error": (
                    f"reference_asset_id {reference_asset_id!r} could not be loaded "
                    f"({e}). Omit it to generate from scratch, or use a valid "
                    f"asset_id from a previous generate_image result."
                ),
            }]

    # 2) Generate and download through the same provider service as Studio.
    try:
        generated = await _generation_service.generate_image(
            prompt=prompt,
            provider=provider,
            model=model,
            source_image=source_image,
            aspect_ratio=aspect_ratio,
            resolution=resolution,
        )
        raw = generated.data
        result = generated.result
    except Exception as e:
        logger.exception("generate_image: provider generation error")
        return [{"error": f"Image generation error: {e}"}]

    fmt = _sniff_image_format(raw)

    # 4) Store the raw bytes (content-addressed; deduped). The bridge re-uploads
    #    these SAME bytes for the chat thumbnail and dedups to this same asset.
    try:
        asset = store.upload(
            raw_bytes=raw,
            original_mime=f"image/{fmt}",
            source=_SOURCE,
            owner_user_id=user_id,
        )
    except Exception as e:
        logger.exception("generate_image: media store upload failed")
        return [{"error": f"Generated image but failed to store it: {e}"}]

    info = {
        "asset_id": asset.id,
        "prompt": prompt,
        "provider": generated.provider,
        "model": generated.model,
        "revised_prompt": result.revised_prompt,
        "reference_asset_id": reference_asset_id,
        "urls": {
            "thumb": f"/v1/uploads/{asset.id}/thumb",
            "preview": f"/v1/uploads/{asset.id}/preview",
            "original": f"/v1/uploads/{asset.id}",
        },
        "hint": (
            "The image is shown above. To refine it, call generate_image again "
            f"with reference_asset_id='{asset.id}' and a prompt describing the change."
        ),
    }

    # 5) Return [image, info]: the Image block is what the model sees (and what
    #    the bridge persists for the chat thumbnail); the dict carries the
    #    asset_id the agent needs to iterate.
    return [Image(data=raw, format=fmt), info]
